server:
  port: 8089
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gr3pea34
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
    
  jpa:
    show-sql: true
    hibernate:  
      ddl-auto: none
      naming:
         implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
         physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
  
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n" 